version: '3'

services:
  app:
    image: almond
    container_name: almond
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '8080:8080'
    expose:
      - 8080
    depends_on:
      - db
      - redis
    networks:
      - app-network
#    stdin_open: true
#    tty: true

  db:
    image: mongo:4.4.2-bionic
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - '27018:27017'
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOSTNAME}
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
    ports:
      - '8081:8081'
    depends_on:
      - db
    networks:
      - app-network

  redis:
    image: redis:6.0.6-alpine
    container_name: redis
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
