version: '3'
volumes:
  almond_data:
    external: true
  node_modules:

networks:
  app-network:
    driver: bridge

services:
  mongo:
    restart: always
    image: mongo:4.1.8-xenial
    container_name: mongo
    env_file:
      - .env
    volumes:
      - almond_data:/data/db
    networks:
      - app-network
    ports:
      - '27017:27017'

  redis:
    container_name: redis
    image: redis
    networks:
      - app-network
    ports:
      - '6379:6379'

  app:
    restart: always
    container_name: almond
    image: almond
    build:
      context: ../../
      dockerfile: Dockerfile
    links:
      - mongo
      - redis
    volumes:
      - node_modules:/usr/app/node_modules
      - ../../:/usr/app
    environment:
      - PORT=5000
      - MONGODB_URI=$MONGODB_URI
      - REDIS_URL=redis://redis:6379
    ports:
      - '5000:5000'
    depends_on:
      - redis
      - mongo
    entrypoint:
      - /usr/app/entrypoint.sh
    expose:
      - 5000
    networks:
      - app-network
#    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js
