version: '3'

services:
  app:
    restart: always
    container_name: almond
    image: almond
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
      - redis
    volumes:
      - node_modules:/home/node/app/node_modules
      - ../../:/home/node/app
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/almond
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

  mongo:
    restart: always
    image: mongo:4.1.8-xenial
    container_name: mongo
    env_file:
      - .env
    volumes:
      - almond_data:/data/db
    networks:
      - app-network
    ports:
      - '27017:27017'

  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    networks:
      - app-network
    ports:
      - '6379:6379'

  webserver:
    image: nginx:1.17.6-alpine
    container_name: webserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email almond.froyo@gmail.com --agree-tos --no-eff-email --staging -d almondhydroponics.com  -d www.almondhydroponics.com

volumes:
  almond_data:
    external: true
  node_modules:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/masha/almond-be/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
