version: '3'

services:
  app:
    container_name: almond
    image: almond
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    environment:
      - MONGO_HOSTNAME=db
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    networks:
      - app-network
    stdin_open: true
    tty: true

  db:
    image: mongo:latest
    container_name: db
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - '27018:27017'
    expose:
      - 27017

  redis:
    container_name: redis
    restart: always
    image: redis:6.0.3-alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    external: true
  node_modules:
